# (string) 网站标题
title: Xia Shuangxi 的只言片语
# (string) 网站说明描述
description: 有关各种编程的主题碎语。有些可能写的不好，有些可能是比较不合实际的想法。不能保证所有的这些都是有用的。

self_github_url: https://www.github.com/xiashuangxi/bookphrase

permalink: /blog/posts/:year/:month/:day/:title:output_ext

# (string) logo 的 URL
logo_url: 

# (string) 博客文件的目录
blog_folder: "blogs"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
 -
    scope:
      path: ""
    values:
      layout: "site-default"
      author: "XIA.SHUANGXI"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "site-page"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "site-post"    

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata

