# (string) 网站标题
title: Xia Shuangxi 的世界 (๑•̀ㅂ•́)و✧
# (string) 网站说明描述
# description: 这个博客里记录着各种各样的主题，有生活、有学习、当然还有一些想法和看法。有些可能写的不好，有些可能不符合实际。我不能保证所有的这些都是有用的。
# description: 这个博客里记录的着各种主题的文章、知识和信息，也有一些对某些事物的不好或不符合实际的看法。不能保证所有的这些都是客观的和有用的。

self_github_url: https://www.github.com/xiashuangxi/bookphrase

permalink: /blog/posts/:year/:month/:day/:title:output_ext

# (string) logo 的 URL
logo_url: 

author: "Xia Shuangxi"
email: "xiashuangxi@hotmail.com"

# (string) 博客文件的目录
blog_folder: "blogs"

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

defaults:
 -
    scope:
      path: ""
    values:
      layout: "site-default"
 -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "site-page"
 -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "site-post"    


plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-github-metadata
  # - jekyll-paginate
